<template><div><h1 id="十二、颜色" tabindex="-1"><a class="header-anchor" href="#十二、颜色"><span>十二、颜色</span></a></h1>
<h2 id="_12-2-使用" tabindex="-1"><a class="header-anchor" href="#_12-2-使用"><span>12.2 使用</span></a></h2>
<p>PixiJS中的 <code v-pre>Color</code> 类是一个用于表示颜色的灵活实用程序。它在整个渲染管道中用于诸如着色、填充、笔画、渐变等。</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> Color<span class="token punctuation">,</span> Sprite<span class="token punctuation">,</span> Texture<span class="token punctuation">,</span> Graphics <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'pixi.js'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> red <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Color</span><span class="token punctuation">(</span><span class="token string">'red'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Named color</span></span>
<span class="line"><span class="token keyword">const</span> green <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Color</span><span class="token punctuation">(</span><span class="token number">0x00ff00</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Hex</span></span>
<span class="line"><span class="token keyword">const</span> blue <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Color</span><span class="token punctuation">(</span><span class="token string">'#0000ff'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Hex string</span></span>
<span class="line"><span class="token keyword">const</span> rgba <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Color</span><span class="token punctuation">(</span><span class="token punctuation">{</span> r<span class="token operator">:</span> <span class="token number">255</span><span class="token punctuation">,</span> g<span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span> b<span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span> a<span class="token operator">:</span> <span class="token number">0.5</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// RGBA object</span></span>
<span class="line"></span>
<span class="line"><span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>red<span class="token punctuation">.</span><span class="token function">toArray</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// [1, 0, 0, 1]</span></span>
<span class="line"><span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>green<span class="token punctuation">.</span><span class="token function">toHex</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// "#00ff00"</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> sprite <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Sprite</span><span class="token punctuation">(</span>Texture<span class="token punctuation">.</span><span class="token constant">WHITE</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">sprite<span class="token punctuation">.</span>tint <span class="token operator">=</span> red<span class="token punctuation">;</span> <span class="token comment">// Works directly with a Color instance</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_12-2-使用-color-和-colorsource" tabindex="-1"><a class="header-anchor" href="#_12-2-使用-color-和-colorsource"><span>12.2 使用 <code v-pre>Color</code> 和 <code v-pre>ColorSource</code></span></a></h2>
<p>PixiJS通过 <code v-pre>ColorSource</code> 类型支持多种颜色格式：</p>
<ul>
<li>颜色名称: <code v-pre>'red'</code> ,  <code v-pre>'white'</code> ,  <code v-pre>'blue'</code> ,等等。</li>
<li>十六进制整数： <code v-pre>0xffcc00</code></li>
<li>十六进制字符串： <code v-pre>'ffcc00'</code> ,  <code v-pre>'#f00'</code> ,  <code v-pre>'0xffcc00ff'</code></li>
<li>RGB(A)对象： <code v-pre>{ r: 255, g: 0, b: 0 }</code> ,  <code v-pre>{ r: 255, g: 0, b: 0, a: 0.5 }</code></li>
<li>RGB(A) string:  <code v-pre>'rgb(255,0,0)'</code> ,  <code v-pre>'rgba(255,0,0,0.5)'</code></li>
<li>RGB(A)阵列： <code v-pre>[1, 0, 0]</code> ,  <code v-pre>[1, 0, 0, 0.5]</code></li>
<li>类型数组： <code v-pre>Uint8Array</code> ,  <code v-pre>Float32Array</code></li>
<li>HSL/HSV对象和字符串</li>
<li><code v-pre>Color</code> 实例</li>
</ul>
<p>当你看到与颜色相关的属性时（例如， <code v-pre>fill</code> ,  <code v-pre>tint</code> ,  <code v-pre>stroke</code> ），你可以使用这些格式中的任何一种。库将在内部自动将它们转换为适当的格式。</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> Graphics<span class="token punctuation">,</span> Sprite<span class="token punctuation">,</span> Texture <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'pixi.js'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> sprite <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Sprite</span><span class="token punctuation">(</span>Texture<span class="token punctuation">.</span><span class="token constant">WHITE</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">sprite<span class="token punctuation">.</span>tint <span class="token operator">=</span> <span class="token string">'red'</span><span class="token punctuation">;</span> <span class="token comment">// converted internally</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> graphics <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Graphics</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">graphics<span class="token punctuation">.</span><span class="token function">fill</span><span class="token punctuation">(</span><span class="token punctuation">{</span> color<span class="token operator">:</span> <span class="token string">'#00ff00'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Also converted internally</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


