<template><div><h1 id="二、vue使用" tabindex="-1"><a class="header-anchor" href="#二、vue使用"><span>二、vue使用</span></a></h1>
<h2 id="_2-1-安装插件" tabindex="-1"><a class="header-anchor" href="#_2-1-安装插件"><span>2.1 安装插件</span></a></h2>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code><span class="line"><span class="token function">npm</span> i tui-image-editor</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="_2-2-组件中使用" tabindex="-1"><a class="header-anchor" href="#_2-2-组件中使用"><span>2.2 组件中使用</span></a></h2>
<div class="language-html line-numbers-mode" data-highlighter="prismjs" data-ext="html"><pre v-pre><code><span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span><span class="token punctuation">></span></span></span>
<span class="line">  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>box<span class="token punctuation">"</span></span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>drawing-container<span class="token punctuation">"</span></span><span class="token punctuation">></span></span></span>
<span class="line">      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>tui-image-editor<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span></span>
<span class="line">  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span></span>
<span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span></span>
<span class="line"></span>
<span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript"></span>
<span class="line"><span class="token keyword">import</span> <span class="token string">"tui-image-editor/dist/tui-image-editor.css"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token string">"tui-color-picker/dist/tui-color-picker.css"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> ImageEditor <span class="token keyword">from</span> <span class="token string">"tui-image-editor"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HelloWorld'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token comment">// components:{ uiMarke },</span></span>
<span class="line">  <span class="token function">data</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token literal-property property">instance</span><span class="token operator">:</span> <span class="token keyword">null</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token function">mounted</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token literal-property property">methods</span><span class="token operator">:</span><span class="token punctuation">{</span></span>
<span class="line">   <span class="token function">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token keyword">this</span><span class="token punctuation">.</span>instance <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ImageEditor</span><span class="token punctuation">(</span></span>
<span class="line">        document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">"#tui-image-editor"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">{</span></span>
<span class="line">          <span class="token literal-property property">includeUI</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token literal-property property">loadImage</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">              <span class="token literal-property property">path</span><span class="token operator">:</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"@/assets/logo.png"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">              <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"image"</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token literal-property property">initMenu</span><span class="token operator">:</span> <span class="token string">"draw"</span><span class="token punctuation">,</span> <span class="token comment">// 默认打开的菜单项</span></span>
<span class="line">            <span class="token literal-property property">menuBarPosition</span><span class="token operator">:</span> <span class="token string">"bottom"</span><span class="token punctuation">,</span> <span class="token comment">// 菜单所在的位置</span></span>
<span class="line">          <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">          <span class="token literal-property property">cssMaxWidth</span><span class="token operator">:</span> <span class="token number">1000</span><span class="token punctuation">,</span> <span class="token comment">// canvas 最大宽度</span></span>
<span class="line">          <span class="token literal-property property">cssMaxHeight</span><span class="token operator">:</span> <span class="token number">600</span><span class="token punctuation">,</span> <span class="token comment">// canvas 最大高度</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">      <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      document<span class="token punctuation">.</span><span class="token function">getElementsByClassName</span><span class="token punctuation">(</span><span class="token string">"tui-image-editor-main"</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>style<span class="token punctuation">.</span>top <span class="token operator">=</span> <span class="token string">"45px"</span><span class="token punctuation">;</span> <span class="token comment">// 图片距顶部工具栏的距离</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span></span>
<span class="line"></span>
<span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>style</span> <span class="token attr-name">scoped</span><span class="token punctuation">></span></span><span class="token style"><span class="token language-css"></span>
<span class="line"><span class="token selector">.box</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token property">width</span><span class="token punctuation">:</span> 100%<span class="token punctuation">;</span></span>
<span class="line">  <span class="token property">height</span><span class="token punctuation">:</span> 100%<span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token selector">.drawing-container</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token property">height</span><span class="token punctuation">:</span> 900px<span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>style</span><span class="token punctuation">></span></span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_2-3-本地化语言为中文" tabindex="-1"><a class="header-anchor" href="#_2-3-本地化语言为中文"><span>2.3 本地化语言为中文</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">data</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token literal-property property">instance</span><span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">locale_zh</span> <span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token literal-property property">ZoomIn</span><span class="token operator">:</span> <span class="token string">"放大"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">ZoomOut</span><span class="token operator">:</span> <span class="token string">"缩小"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Hand</span><span class="token operator">:</span> <span class="token string">"手掌"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">History</span><span class="token operator">:</span> <span class="token string">'历史'</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Resize</span><span class="token operator">:</span> <span class="token string">'调整宽高'</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Crop</span><span class="token operator">:</span> <span class="token string">"裁剪"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">DeleteAll</span><span class="token operator">:</span> <span class="token string">"全部删除"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Delete</span><span class="token operator">:</span> <span class="token string">"删除"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Undo</span><span class="token operator">:</span> <span class="token string">"撤销"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Redo</span><span class="token operator">:</span> <span class="token string">"反撤销"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Reset</span><span class="token operator">:</span> <span class="token string">"重置"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Flip</span><span class="token operator">:</span> <span class="token string">"镜像"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Rotate</span><span class="token operator">:</span> <span class="token string">"旋转"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Draw</span><span class="token operator">:</span> <span class="token string">"画"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Shape</span><span class="token operator">:</span> <span class="token string">"形状标注"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Icon</span><span class="token operator">:</span> <span class="token string">"图标标注"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Text</span><span class="token operator">:</span> <span class="token string">"文字标注"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Mask</span><span class="token operator">:</span> <span class="token string">"遮罩"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Filter</span><span class="token operator">:</span> <span class="token string">"滤镜"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Bold</span><span class="token operator">:</span> <span class="token string">"加粗"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Italic</span><span class="token operator">:</span> <span class="token string">"斜体"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Underline</span><span class="token operator">:</span> <span class="token string">"下划线"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Left</span><span class="token operator">:</span> <span class="token string">"左对齐"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Center</span><span class="token operator">:</span> <span class="token string">"居中"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Right</span><span class="token operator">:</span> <span class="token string">"右对齐"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Color</span><span class="token operator">:</span> <span class="token string">"颜色"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Text size"</span><span class="token operator">:</span> <span class="token string">"字体大小"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Custom</span><span class="token operator">:</span> <span class="token string">"自定义"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Square</span><span class="token operator">:</span> <span class="token string">"正方形"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Apply</span><span class="token operator">:</span> <span class="token string">"应用"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Cancel</span><span class="token operator">:</span> <span class="token string">"取消"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Flip X"</span><span class="token operator">:</span> <span class="token string">"X 轴"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Flip Y"</span><span class="token operator">:</span> <span class="token string">"Y 轴"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Range</span><span class="token operator">:</span> <span class="token string">"区间"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Stroke</span><span class="token operator">:</span> <span class="token string">"描边"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Fill</span><span class="token operator">:</span> <span class="token string">"填充"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Circle</span><span class="token operator">:</span> <span class="token string">"圆"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Triangle</span><span class="token operator">:</span> <span class="token string">"三角"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Rectangle</span><span class="token operator">:</span> <span class="token string">"矩形"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Free</span><span class="token operator">:</span> <span class="token string">"曲线"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Straight</span><span class="token operator">:</span> <span class="token string">"直线"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Arrow</span><span class="token operator">:</span> <span class="token string">"箭头"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Arrow-2"</span><span class="token operator">:</span> <span class="token string">"箭头2"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Arrow-3"</span><span class="token operator">:</span> <span class="token string">"箭头3"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Star-1"</span><span class="token operator">:</span> <span class="token string">"星星1"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Star-2"</span><span class="token operator">:</span> <span class="token string">"星星2"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Polygon</span><span class="token operator">:</span> <span class="token string">"多边形"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Location</span><span class="token operator">:</span> <span class="token string">"定位"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Heart</span><span class="token operator">:</span> <span class="token string">"心形"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Bubble</span><span class="token operator">:</span> <span class="token string">"气泡"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Custom icon"</span><span class="token operator">:</span> <span class="token string">"自定义图标"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Load Mask Image"</span><span class="token operator">:</span> <span class="token string">"加载蒙层图片"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Grayscale</span><span class="token operator">:</span> <span class="token string">"灰度"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Blur</span><span class="token operator">:</span> <span class="token string">"模糊"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Sharpen</span><span class="token operator">:</span> <span class="token string">"锐化"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Emboss</span><span class="token operator">:</span> <span class="token string">"浮雕"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Remove White"</span><span class="token operator">:</span> <span class="token string">"除去白色"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Distance</span><span class="token operator">:</span> <span class="token string">"距离"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Brightness</span><span class="token operator">:</span> <span class="token string">"亮度"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Noise</span><span class="token operator">:</span> <span class="token string">"噪音"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Color Filter"</span><span class="token operator">:</span> <span class="token string">"彩色滤镜"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Sepia</span><span class="token operator">:</span> <span class="token string">"棕色"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Sepia2</span><span class="token operator">:</span> <span class="token string">"棕色2"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Invert</span><span class="token operator">:</span> <span class="token string">"负片"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Pixelate</span><span class="token operator">:</span> <span class="token string">"像素化"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Threshold</span><span class="token operator">:</span> <span class="token string">"阈值"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Tint</span><span class="token operator">:</span> <span class="token string">"色调"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Multiply</span><span class="token operator">:</span> <span class="token string">"正片叠底"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Blend</span><span class="token operator">:</span> <span class="token string">"混合色"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Width</span><span class="token operator">:</span> <span class="token string">"宽度"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">Height</span><span class="token operator">:</span> <span class="token string">"高度"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"Lock Aspect Ratio"</span><span class="token operator">:</span> <span class="token string">"锁定宽高比例"</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token literal-property property">methods</span><span class="token operator">:</span><span class="token punctuation">{</span></span>
<span class="line">   <span class="token function">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token keyword">this</span><span class="token punctuation">.</span>instance <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ImageEditor</span><span class="token punctuation">(</span></span>
<span class="line">        document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">"#tui-image-editor"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">{</span></span>
<span class="line">          <span class="token literal-property property">includeUI</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token literal-property property">loadImage</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">              <span class="token literal-property property">path</span><span class="token operator">:</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"@/assets/logo.png"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">              <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"image"</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token literal-property property">initMenu</span><span class="token operator">:</span> <span class="token string">"draw"</span><span class="token punctuation">,</span> <span class="token comment">// 默认打开的菜单项</span></span>
<span class="line">            <span class="token literal-property property">menuBarPosition</span><span class="token operator">:</span> <span class="token string">"bottom"</span><span class="token punctuation">,</span> <span class="token comment">// 菜单所在的位置</span></span>
<span class="line">            <span class="token literal-property property">locale</span><span class="token operator">:</span> <span class="token keyword">this</span><span class="token punctuation">.</span>locale_zh<span class="token punctuation">,</span> <span class="token comment">// 本地化语言为中文</span></span>
<span class="line">          <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">          <span class="token literal-property property">cssMaxWidth</span><span class="token operator">:</span> <span class="token number">1000</span><span class="token punctuation">,</span> <span class="token comment">// canvas 最大宽度</span></span>
<span class="line">          <span class="token literal-property property">cssMaxHeight</span><span class="token operator">:</span> <span class="token number">600</span><span class="token punctuation">,</span> <span class="token comment">// canvas 最大高度</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">      <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      document<span class="token punctuation">.</span><span class="token function">getElementsByClassName</span><span class="token punctuation">(</span><span class="token string">"tui-image-editor-main"</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>style<span class="token punctuation">.</span>top <span class="token operator">=</span> <span class="token string">"45px"</span><span class="token punctuation">;</span> <span class="token comment">// 图片距顶部工具栏的距离</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_2-4-修改样式" tabindex="-1"><a class="header-anchor" href="#_2-4-修改样式"><span>2.4 修改样式</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">data</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token literal-property property">instance</span><span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">customTheme</span> <span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token string-property property">"common.bi.image"</span><span class="token operator">:</span> <span class="token string">""</span><span class="token punctuation">,</span> <span class="token comment">// 左上角logo图片</span></span>
<span class="line">        <span class="token string-property property">"common.bisize.width"</span><span class="token operator">:</span> <span class="token string">"0px"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"common.bisize.height"</span><span class="token operator">:</span> <span class="token string">"0px"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"common.backgroundImage"</span><span class="token operator">:</span> <span class="token string">"none"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"common.backgroundColor"</span><span class="token operator">:</span> <span class="token string">"#f3f4f6"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"common.border"</span><span class="token operator">:</span> <span class="token string">"1px solid #333"</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// header</span></span>
<span class="line">        <span class="token string-property property">"header.backgroundImage"</span><span class="token operator">:</span> <span class="token string">"none"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"header.backgroundColor"</span><span class="token operator">:</span> <span class="token string">"#f3f4f6"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"header.border"</span><span class="token operator">:</span> <span class="token string">"0px"</span><span class="token punctuation">,</span></span>
<span class="line">        </span>
<span class="line">        <span class="token comment">// load button</span></span>
<span class="line">        <span class="token string-property property">"loadButton.backgroundColor"</span><span class="token operator">:</span> <span class="token string">"#fff"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"loadButton.border"</span><span class="token operator">:</span> <span class="token string">"1px solid #ddd"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"loadButton.color"</span><span class="token operator">:</span> <span class="token string">"#222"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"loadButton.fontFamily"</span><span class="token operator">:</span> <span class="token string">"NotoSans, sans-serif"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"loadButton.fontSize"</span><span class="token operator">:</span> <span class="token string">"12px"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"loadButton.display"</span><span class="token operator">:</span> <span class="token string">"none"</span><span class="token punctuation">,</span> <span class="token comment">// 隐藏</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// download button</span></span>
<span class="line">        <span class="token string-property property">"downloadButton.backgroundColor"</span><span class="token operator">:</span> <span class="token string">"#fdba3b"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"downloadButton.border"</span><span class="token operator">:</span> <span class="token string">"1px solid #fdba3b"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"downloadButton.color"</span><span class="token operator">:</span> <span class="token string">"#fff"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"downloadButton.fontFamily"</span><span class="token operator">:</span> <span class="token string">"NotoSans, sans-serif"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"downloadButton.fontSize"</span><span class="token operator">:</span> <span class="token string">"12px"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"downloadButton.display"</span><span class="token operator">:</span> <span class="token string">"none"</span><span class="token punctuation">,</span> <span class="token comment">// 隐藏</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// icons default</span></span>
<span class="line">        <span class="token string-property property">"menu.normalIcon.color"</span><span class="token operator">:</span> <span class="token string">"#8a8a8a"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"menu.activeIcon.color"</span><span class="token operator">:</span> <span class="token string">"#555555"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"menu.disabledIcon.color"</span><span class="token operator">:</span> <span class="token string">"#ccc"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"menu.hoverIcon.color"</span><span class="token operator">:</span> <span class="token string">"#e9e9e9"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"submenu.normalIcon.color"</span><span class="token operator">:</span> <span class="token string">"#8a8a8a"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"submenu.activeIcon.color"</span><span class="token operator">:</span> <span class="token string">"#e9e9e9"</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">        <span class="token string-property property">"menu.iconSize.width"</span><span class="token operator">:</span> <span class="token string">"24px"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"menu.iconSize.height"</span><span class="token operator">:</span> <span class="token string">"24px"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"submenu.iconSize.width"</span><span class="token operator">:</span> <span class="token string">"32px"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"submenu.iconSize.height"</span><span class="token operator">:</span> <span class="token string">"32px"</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// submenu primary color</span></span>
<span class="line">        <span class="token string-property property">"submenu.backgroundColor"</span><span class="token operator">:</span> <span class="token string">"#1e1e1e"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"submenu.partition.color"</span><span class="token operator">:</span> <span class="token string">"#858585"</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// submenu labels</span></span>
<span class="line">        <span class="token string-property property">"submenu.normalLabel.color"</span><span class="token operator">:</span> <span class="token string">"#858585"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"submenu.normalLabel.fontWeight"</span><span class="token operator">:</span> <span class="token string">"lighter"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"submenu.activeLabel.color"</span><span class="token operator">:</span> <span class="token string">"#fff"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"submenu.activeLabel.fontWeight"</span><span class="token operator">:</span> <span class="token string">"lighter"</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// checkbox style</span></span>
<span class="line">        <span class="token string-property property">"checkbox.border"</span><span class="token operator">:</span> <span class="token string">"1px solid #ccc"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"checkbox.backgroundColor"</span><span class="token operator">:</span> <span class="token string">"#fff"</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// rango style</span></span>
<span class="line">        <span class="token string-property property">"range.pointer.color"</span><span class="token operator">:</span> <span class="token string">"#fff"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"range.bar.color"</span><span class="token operator">:</span> <span class="token string">"#666"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"range.subbar.color"</span><span class="token operator">:</span> <span class="token string">"#d1d1d1"</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">        <span class="token string-property property">"range.disabledPointer.color"</span><span class="token operator">:</span> <span class="token string">"#414141"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"range.disabledBar.color"</span><span class="token operator">:</span> <span class="token string">"#282828"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"range.disabledSubbar.color"</span><span class="token operator">:</span> <span class="token string">"#414141"</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">        <span class="token string-property property">"range.value.color"</span><span class="token operator">:</span> <span class="token string">"#fff"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"range.value.fontWeight"</span><span class="token operator">:</span> <span class="token string">"lighter"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"range.value.fontSize"</span><span class="token operator">:</span> <span class="token string">"11px"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"range.value.border"</span><span class="token operator">:</span> <span class="token string">"1px solid #353535"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"range.value.backgroundColor"</span><span class="token operator">:</span> <span class="token string">"#151515"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"range.title.color"</span><span class="token operator">:</span> <span class="token string">"#fff"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"range.title.fontWeight"</span><span class="token operator">:</span> <span class="token string">"lighter"</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// colorpicker style</span></span>
<span class="line">        <span class="token string-property property">"colorpicker.button.border"</span><span class="token operator">:</span> <span class="token string">"1px solid #1e1e1e"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">"colorpicker.title.color"</span><span class="token operator">:</span> <span class="token string">"#fff"</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token literal-property property">methods</span><span class="token operator">:</span><span class="token punctuation">{</span></span>
<span class="line">   <span class="token function">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token keyword">this</span><span class="token punctuation">.</span>instance <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ImageEditor</span><span class="token punctuation">(</span></span>
<span class="line">        document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">"#tui-image-editor"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">{</span></span>
<span class="line">          <span class="token literal-property property">includeUI</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token literal-property property">loadImage</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">              <span class="token literal-property property">path</span><span class="token operator">:</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"@/assets/logo.png"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">              <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"image"</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token literal-property property">initMenu</span><span class="token operator">:</span> <span class="token string">"draw"</span><span class="token punctuation">,</span> <span class="token comment">// 默认打开的菜单项</span></span>
<span class="line">            <span class="token literal-property property">menuBarPosition</span><span class="token operator">:</span> <span class="token string">"bottom"</span><span class="token punctuation">,</span> <span class="token comment">// 菜单所在的位置</span></span>
<span class="line">            <span class="token literal-property property">locale</span><span class="token operator">:</span> <span class="token keyword">this</span><span class="token punctuation">.</span>locale_zh<span class="token punctuation">,</span> <span class="token comment">// 本地化语言为中文</span></span>
<span class="line">            <span class="token literal-property property">theme</span><span class="token operator">:</span> <span class="token keyword">this</span><span class="token punctuation">.</span>customTheme<span class="token punctuation">,</span> <span class="token comment">// 自定义样式</span></span>
<span class="line">          <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">          <span class="token literal-property property">cssMaxWidth</span><span class="token operator">:</span> <span class="token number">1000</span><span class="token punctuation">,</span> <span class="token comment">// canvas 最大宽度</span></span>
<span class="line">          <span class="token literal-property property">cssMaxHeight</span><span class="token operator">:</span> <span class="token number">600</span><span class="token punctuation">,</span> <span class="token comment">// canvas 最大高度</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">      <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      document<span class="token punctuation">.</span><span class="token function">getElementsByClassName</span><span class="token punctuation">(</span><span class="token string">"tui-image-editor-main"</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>style<span class="token punctuation">.</span>top <span class="token operator">=</span> <span class="token string">"45px"</span><span class="token punctuation">;</span> <span class="token comment">// 图片距顶部工具栏的距离</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


